# Generated by Django 4.2.6 on 2023-11-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_postdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostdetailTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bookname', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=200)),
                ('Content', models.TextField()),
                ('Publiccationdate', models.CharField(max_length=20)),
                ('State', models.CharField(choices=[('館藏中', '館藏中'), ('預約中', '預約中'), ('借出中', '借出中')], max_length=8)),
                ('Img', models.TextField()),
            ],
        ),
    ]
